version: 2

jobs:
  build_image:
    docker:
      - image: docker:18.05.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build test image
          command: docker build -t test:latest .
  run_container_1:
    docker:
      - image: test:latest
    steps:
      - checkout
      - run:
          name: run command using pre-built image in the workflow
          command: test_1.sh
  run_container_2:
    docker:
      - image: test:latest
    steps:
      - checkout
      - run:
          name: create artifacts using pre-built image in the workflow
          command: test_2.sh
      - store_artifacts:
          path: artifacts

workflows:
  version: 2
  build_and_run:
    jobs:
      - build_image
      - run_container_1:
          requires:
            - build_image
      - run_container_2:
          requires:
            - build_image
